# ----
# Site

title: ServiceStack
description: ServiceStack Framework
environment: production
url: https://servicestack.net
content_url: https://servicestack.net
account_url: https://account.servicestack.net
repository: mythz/site
google_analytics_key: UA-7722718-7
content_separator: <!--separator-->

package_version: 5.*

collections:
  pages:
    title: ServiceStack
    output: true
    permalink: /:slug/
  whatsnew:
    title: Latest features & highlights
    output: true
  news:
    title: News
    output: true
    permalink: /news/:slug/

plugins:
  - github-pages
  - jekyll-paginate-v2

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

# https://github.com/helaili/jekyll-action/issues/43
exclude:
  - readme.md
  - LICENCE
  - .idea/
  - vendor/bundle
  - node_modules
  - package.json
  - src

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: pages
    values:
      priority: 999
      layout: content-page

