# ----
# Site

title: ServiceStack
description: ServiceStack Framework
url: http://site.servicestack.com
repository: mythz/site
google_analytics_key:

package_version: 5.*

collections:
  pages:
    title: ServiceStack
    output: true
    permalink: /:slug.html
plugins:
  - github-pages

exclude:
  - readme.md
  - LICENCE
  - .idea/

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: pages
    values:
      priority: 999
      layout: content-page

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed
