# ----
# Site

title: ServiceStack
description: ServiceStack Framework
environment: production
url: https://site.servicestack.com
content_url: https://site.servicestack.com
account_url: https://account.servicestack.net
repository: mythz/site
google_analytics_key:

package_version: 5.*

collections:
  pages:
    title: ServiceStack
    output: true
    permalink: /:slug.html
plugins:
  - github-pages

# https://github.com/helaili/jekyll-action/issues/43
exclude:
  - readme.md
  - LICENCE
  - .idea/
  - vendor/bundle
  - node_modules
  - package.json
  - src

topics: []
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      collection: pages
    values:
      priority: 999
      layout: content-page

# -----
# Build
sass:
  sass_dir: _scss
  style: :compressed
